export const Products = [
  {
    id: 1,
    name: "Mchele + Ndengu",
    price: 170,
    discount: "-11 % ",
    priceBefore: 190,
  },
  {
    id: 2,
    name: "Mchele + Kamande",
    price: 170,
    discount: "-9 % ",
    priceBefore: 190,
  },
  {
    id: 3,
    name: "Mchele + Minced Meat",
    price: 200,
    discount: "-10 % ",
    priceBefore: 210,
  },
  {
    id: 4,
    name: "Mchele + Minji",
    price: 170,
    discount: "-8 % ",
    priceBefore: 180,
  },
  {
    id: 5,
    name: "Mchele + Yellow Beans",
    price: 170,
    discount: "-13 % ",
    priceBefore: 180,
  },
  {
    id: 6,
    name: "Chapo(2) + Ndengu",
    price: 170,
    discount: "-12 % ",
    priceBefore: 190,
  },
  {
    id: 7,
    name: "Chapo(2) + Kamande",
    price: 170,
    discount: "-9 % ",
    priceBefore: 180,
  },
  {
    id: 8,
    name: "Chapo(2) + Minced Meat",
    price: 200,
    discount: "-8 % ",
    priceBefore: 210,
  },
  {
    id: 9,
    name: "Chapo(2) + Minji",
    price: 170,
    discount: "-8 % ",
    priceBefore: 190,
  },
  {
    id: 10,
    name: "Chapo(2) + Yellow Beans",
    price: 170,
    discount: "-8 % ",
    priceBefore: 180,
  },
  {
    id: 11,
    name: "Githeri",
    price: 150,
    discount: "-8 % ",
    priceBefore: 160,
  },
  {
    id: 12,
    name: "Bhajia",
    price: 150,
    discount: "-8 % ",
    priceBefore: 155,
  },
];
